#' List of sciNMF built-in gene sets data.frame
#'
#' A list of annotation of TERM TO GENE mapping data.frames, which have 2 column with term and gene. The data.frame is generated by \code{\link[gson]{read.gmt}}
#'
#' @usage ls_gs_sciNMF[["GO_BP"]]
#' @format
#' A list with 5 TERM TO GENE mapping data.frames:
#' \itemize{
#'   \item\code{CellMarker}: generated from CellMarker_Augmented_2021.txt
#'   \item\code{GO_BP}: generated from GO_Biological_Process_2023.txt
#'   \item\code{GO_CC}: generated from GO_Cellular_Component_2023.txt
#'   \item\code{GO_MF}: generated from GO_Molecular_Function_2023.txt
#'   \item\code{Hallmark}: generated from MSigDB_Hallmark_2020.txt
#' }
#' @examples data("ls_gs_sciNMF")
#' @seealso \code{\link[gson]{read.gmt}} for gene.set data.frame generation.
#' @source \url{https://maayanlab.cloud/Enrichr/#libraries}
"ls_gs_sciNMF"
