#' Enrichment Dot Plot
#'
#' Visualize the enrichment results of transciptome programs using a dot plot. The function takes a list of enrichment results generated by \code{\link{PGEnricher}} as input and plots the top enriched terms for each program by \code{\link{ggplot2}}.
#'
#' @param enrich.list A list of enrichment results generated by \code{\link{PGEnricher}}
#'
#' @param top The number of top enriched terms to be shown for each program.
#'
#' @param only.top A logical value indicating whether to plot only the top enriched terms (TRUE) or all enriched terms that are part of the top enriched pathways (FALSE).
#'
#' @param color A vector of colors to be used in the dot plot. The length of the vector should be at least the number of terms being plotted. The default is \code{paletteer::paletteer_dynamic("cartography::red.pal", 20)[10:20]}.
#'
#' @return A ggplot object representing the enrichment dot plot.
#'
#' @import ggplot2
#' @importFrom paletteer paletteer_dynamic
#' @importFrom utils  head
#'
#' @seealso \code{\link[ggplot2]{ggplot}} for customizing the plot appearance.
#'
#'
#' @export
#'
EnrichDotPlot = function(enrich.list, top = 3, only.top = TRUE, color = paletteer_dynamic("cartography::red.pal", 20)[10:20]){
    if(inherits(enrich.list[[1]], "enrichResult")){
        enrich.list = lapply(enrich.list, function(enrich){enrich@result})
    }

    if(only.top){

        df_pl = lapply(setNames(names(enrich.list), names(enrich.list)), function(sig){

            if (nrow(enrich.list[[sig]]) == 0){
                warning("The ", sig, " has no significant enrich result")
                return()
            }

            sub_df = head(enrich.list[[sig]], n = top)
            sub_df$Name = sig
            return(sub_df)
        }) %>% do.call(what = rbind)
        df_pl$Description = factor(df_pl$Description, levels = unique(df_pl$Description))

    }else{

        pw = lapply(setNames(names(enrich.list), names(enrich.list)),function(sig){

            if(nrow(enrich.list[[sig]])==0){
                warning('The ',sig, ' has no significant enrich result')
                return()
            }

            head(enrich.list[[sig]], n = top)$ID
        }) %>% unlist %>% unique

        df_pl = lapply(setNames(names(enrich.list), names(enrich.list)),function(sig){

            if(nrow(enrich.list[[sig]])==0){
                return()
            }

            idx_pw = enrich.list[[sig]]$ID %in% pw

            sub_df = enrich.list[[sig]][idx_pw,]
            sub_df$Name = sig
            return(sub_df)
        }) %>% do.call(what = rbind)

        df_pl$Description = factor(df_pl$Description,
                                   levels = setNames(unique(df_pl$Description), unique(df_pl$ID))[pw])
    }

    df_pl$Name = factor(df_pl$Name,
                        levels = names(enrich.list))
    df_pl$Nlgp = -log(df_pl$p.adjust)

    df_pl$GeneRatio = strsplit(df_pl$GeneRatio,split = '/') %>% sapply(function(v){
        v = as.numeric(v)
        return(v[1]/v[2])
    })
    pl = ggplot(df_pl, aes(x = Name, y = Description)) +
        xlab('') + ylab('')+
        theme_bw() +
        geom_point(aes(color = Nlgp, size = GeneRatio)) +
        scale_color_gradientn(colors = color, name = '-log10 p.adj') +
        theme(axis.text.x = element_text(angle = 60,hjust = 1)) +
        theme(axis.text = element_text(face = 'bold'))

    return(pl)
}
